version: '3'
services:
  rclone:
    image: rclone/rclone
    container_name: rclone
    ports:
      - "5572:5572"
    #volumes:
    #  - /path/to/rclone/config:/config/rclone
    #  - /path/to/data:/data
    command: rcd --rc-web-gui --rc-addr=:5572 --rc-user=test1 --rc-pass=password
