services:
  mesh-router:
    image: nasselle/mesh-router
    restart: unless-stopped
    # necessary conf for wireguard
    # https://hub.docker.com/r/linuxserver/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      # Enable IPv4 forwarding
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - PROVIDER=%PROVIDER_STR%
    networks:
      - pcs

  casaos:
    image: nasselle/casa-img
    restart: unless-stopped
    environment:
      - DATA_ROOT=/DATA
      - REF_NET=pcs
      - REF_DOMAIN=%DOMAIN%
      - REF_SCHEME=https
      - REF_PORT=443
    volumes:
      - /DATA:/DATA
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - pcs

networks:
  pcs:
    driver: bridge
    name: pcs