services:
  mesh-router:
    image: nasselle/mesh-router
    cap_add:
      - NET_ADMIN
    environment:
      - PROVIDER=%PROVIDER_STR%
    networks:
      - nasselle

  casaos:
    image: nasselle/casa-img
    environment:
      - DATA_ROOT=/DATA
      - REF_NET=nasselle
      - REF_DOMAIN=%DOMAIN%
    volumes:
      - /DATA:/DATA
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nasselle

networks:
  nasselle:
    driver: bridge
    name: nasselle